input_task:
  description: >
    Collect and process the raw textual description provided by the user: {description}
    Your job is to understand the content, whether it's a job posting, project description, 
    or any other subject matter, and ensure it's ready for further processing.
  expected_output: >
    The complete raw description with any clarifications or structured formatting that might help in further analysis.
  agent: input_agent

refinement_task:
  description: >
    Clean and standardize the following input description from the previous agent output.
    Remove any spelling errors, eliminate repetitive content, clarify ambiguous language,
    and organize the content in a structured format suitable for skill extraction.
  expected_output: >
    A polished, well-structured, and refined description with clear points and organized sections.
  agent: refining_agent

analysis_task:
  description: >
    Identify both technical and non-technical skills from the refined description provided by the previous agent.
    Focus on extracting specific tools, programming languages, frameworks, methodologies, platforms,
    soft skills, and any other competencies mentioned explicitly or implied in the content.
  expected_output: >
    A detailed and categorized list of all required skills, competencies, and expertise with clear organization.
  agent: analysis_agent

validation_task:
  description: >
    Cross-check the extracted skills against the original description.
    Verify that all extracted skills are relevant to the context, nothing vital is missing,
    and no inappropriate or irrelevant skills are included. Check for industry-specific requirements.
  expected_output: >
    A validated, accurate, and comprehensive list of skills with confidence ratings and justification.
  agent: validation_agent

output_task:
  description: >
    Format and present the validated list of skills from the previous task outputs.
    Create a well-structured report that categorizes skills by type (technical, soft skills, etc.),
    importance level, and includes brief explanations of why each skill is relevant.
  expected_output: >
    A professional, comprehensive skills report in markdown format with clear sections, categorization,
    and explanations that would be immediately useful to someone reviewing the skill requirements.
  agent: output_agent
